trigger:
  branches:
    include:
      - main

pool: Laptop   # 👈 use Microsoft-hosted agent (change if you want self-hosted)

variables: 
  buildConfiguration: 'Release'
  projectSolution: '**/IT_Hardware.sln'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

stages:
# ------------------------------
# 1. Build & Test + SonarCloud
# ------------------------------
- stage: BuildAndTest
  displayName: "Build, Test & SonarCloud"
  jobs:
  - job: Build
    steps:
      - checkout: self

      # Install .NET 9 Preview SDK
      - task: UseDotNet@2
        displayName: "Use .NET 9.0.x SDK"
        inputs:
          packageType: 'sdk'
          version: '9.0.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: |
          echo "##vso[task.setvariable variable=DOTNET_ROOT]$(Agent.ToolsDirectory)/dotnet"
          echo "##vso[task.setvariable variable=PATH]$(Agent.ToolsDirectory)/dotnet;$(PATH)"
        displayName: "Set DOTNET_ROOT"

      - script: dotnet --info
        displayName: "Check .NET SDK Version"

      # Restore
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: 'restore'
          projects: '$(projectSolution)'

      # SonarCloud Prepare (FIXED service connection name)
      - task: SonarCloudPrepare@3
        inputs:
          SonarCloud: 'sonarcube'   # 👈 must match your service connection name
          organization: 'hrisikeshkumar'
          scannerMode: 'dotnet'
          projectKey: 'hrisikeshkumar_itassetshq'
          projectName: 'ITAssetsHQ'

      # Build
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: '$(projectSolution)'
          arguments: '--configuration $(buildConfiguration)'

      # Test
      - task: DotNetCoreCLI@2
        displayName: "Run Unit Tests"
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
          arguments: '--configuration $(buildConfiguration) --no-build --logger trx --results-directory $(Build.SourcesDirectory)/TestResults'

      # Publish Test Results
      - task: PublishTestResults@2
        displayName: "Publish Unit Test Results"
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/TestResults/*.trx'
          searchFolder: '$(Build.SourcesDirectory)/TestResults'
          failTaskOnFailedTests: true

      # SonarCloud Analyze & Publish
      - task: SonarCloudAnalyze@3
      - task: SonarCloudPublish@3
        inputs:
          pollingTimeoutSec: '300'

# ------------------------------
# 2. Package & Publish Artifacts
# ------------------------------
- stage: Package
  displayName: "Package & Publish"
  dependsOn: BuildAndTest
  jobs:
  - job: PackageJob
    steps:
      - checkout: self
        clean: true

      - task: UseDotNet@2
        displayName: "Use .NET 9.0.x SDK"
        inputs:
          packageType: 'sdk'
          version: '9.0.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - script: |
          echo "##vso[task.setvariable variable=DOTNET_ROOT]$(Agent.ToolsDirectory)/dotnet"
          echo "##vso[task.setvariable variable=PATH]$(Agent.ToolsDirectory)/dotnet;$(PATH)"
        displayName: "Set DOTNET_ROOT"

      - script: dotnet --info
        displayName: "Check .NET SDK Version"

      - task: DotNetCoreCLI@2
        displayName: "Publish"
        inputs:
          command: 'publish'
          projects: '$(projectSolution)'
          arguments: '--configuration $(buildConfiguration) --output $(publishDir)'

      # Archive publish output into a ZIP (for deployment)
      - task: ArchiveFiles@2
        displayName: "Archive Published Files"
        inputs:
          rootFolderOrFile: '$(publishDir)'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifacts"
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
          artifactName: 'drop'
          publishLocation: 'Container'

# ------------------------------
# 3. Deploy to Azure (staging)
# ------------------------------
- stage: Deploy
  displayName: "Deploy to Azure App Service"
  dependsOn: Package
  jobs:
  - deployment: DeployWeb
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                artifactName: 'drop'
                downloadPath: '$(Pipeline.Workspace)'

            - task: AzureWebApp@1
              displayName: 'Deploy to Azure WebApp (Staging)'
              inputs:
                azureSubscription: 'Azure'   # 👈 must match your Azure service connection
                appName: 'rajaicsi'
                package: '$(Pipeline.Workspace)/drop/app.zip'
